name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm i
      - name: Build SPA
        run: npm run build:spa && cp './.htaccess' './dist/.htaccess'
      - name: Deploy SPA
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'
      - name: Build SSR
        run: |
          npm run build
          cp './worker-site/wrangler.toml.example' './worker-site/wrangler.toml'
      - name: Edit wrangler.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: './worker-site/wrangler.toml'
          key: 'account_id'
          value: ${{ secrets.CF_ACCOUNT_ID }}
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'worker-site'